# <span style="color:red"> QTM 151 - Quiz 3 </span>

## Please submit as an HTML file

<font size = "5" >
This quiz is open book 

- You can use the lecture notes
- You will get partial credit for attempting the questions
- To get full credit, the code should run as intended
- You should <span style="color:red"> NOT </span> communicate with other students

Print the following message: <br>

"I will abide by Emory's code of conduct"

In [ ]:
# Write your answer here:

print("I will abide by Emory's code of conduct.")

<font size = "5">

Import the libraries "numpy" and "pandas"

In [1]:
import numpy as np 
import pandas as pd


<font size = "5">

(1) Replace values in a column

<font size = "3">

- Load the data from "constructors.csv", assigning it to a DataFrame.
- In the "nationality" column, replace the values "British", "Japanese", and "Irish" with "UK", "Japan", and "Ireland", respectively.
- For full credit, do this by using the ``.replace`` command **one time**

In [5]:
# Your answer here

constructors = pd.read_csv("data_raw/constructors.csv")
constructors["nationality"] = constructors["nationality"].replace({
    "British": "UK",
    "Japanese": "Japan",
    "Irish": "Ireland"
})
constructors

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,UK,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,UK,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
...,...,...,...,...,...
206,209,manor,Manor Marussia,UK,http://en.wikipedia.org/wiki/Manor_Motorsport
207,210,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team
208,211,racing_point,Racing Point,UK,http://en.wikipedia.org/wiki/Racing_Point_F1_Team
209,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri
210,214,alpine,Alpine F1 Team,French,http://en.wikipedia.org/wiki/Alpine_F1_Team

<font size = "5">

(2) Aggregate and query

<font size = "3">

Import the data from "sprint_results.csv" and assign it to a DataFrame. Do the following:

- Extract the subset corresponding to 'constructorId == 51' using ```.query()```
- Group by the column "driverId", and then aggregate the maximum over the "laps" column for each driver.
- Extract the subset of drivers with maximum of laps $\ge 20$. Assign this to a DataFrame with a name of your choice.

For full credit, perform all the steps in bullet points above in a **single line** using chaining. (If you use line breaks or wrap in parentheses it doesn't literally need to be one line).

**Hint:** I only see your final submission, not the code you wrote along the way. It might be easier to break it up into multiple lines, then combine when you're done.

In [22]:
# Your answer here
sprint = pd.read_csv("data_raw/sprint_results.csv")

max_lap = (sprint.query("constructorId == 51")
                     .groupby("driverId")
                     .agg(max_laps = ("laps", "max"))
                     .query("max_laps >= 20"))

sprint

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,fastestLapTime,statusId
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,116,1095,840,117,18,15,16,16,16,0,24,+50.700,1862007,4,1:15.425,1
116,117,1095,839,214,31,6,17,17,17,0,24,+51.756,1863063,5,1:16.097,1
117,118,1095,4,214,14,7,18,18,18,0,24,+53.985,1865292,5,1:14.764,1
118,119,1095,849,3,6,16,19,19,19,0,24,+1:16.850,1888157,4,1:16.525,1
119,120,1095,848,3,23,11,\N,R,20,0,12,\N,\N,4,1:15.998,31

<font size = "5">

(3) Recode a numeric column

<font size = "3">

- Import data from "races.csv" and assign it to a DataFrame
- Recode the "year" column into a new column "year_brackets"
with the following categories

$\qquad$ ``` ["1950-1965","1966-1980","1981-onwards"] ```

The easiest method is ``pd.cut()`` but you are not required to use this.

In [24]:
# Your answer here

races = pd.read_csv("data_raw/races.csv")

races["year_brackets"] = pd.cut(
    races["year"],
    bins = [1949, 1965, 1980, float("inf")],
    labels = ["1950-1965", "1966-1980", "1981-onwards"]
)

races

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time,year_brackets
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1981-onwards
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1981-onwards
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1981-onwards
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1981-onwards
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1981-onwards
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1097,1116,2023,19,69,United States Grand Prix,2023-10-22,19:00:00,https://en.wikipedia.org/wiki/2023_United_Stat...,2023-10-20,17:30:00,2023-10-21,18:00:00,\N,\N,2023-10-20,21:00:00,2023-10-21,22:00:00,1981-onwards
1098,1117,2023,20,32,Mexico City Grand Prix,2023-10-29,20:00:00,https://en.wikipedia.org/wiki/2023_Mexico_City...,2023-10-27,18:30:00,2023-10-27,22:00:00,2023-10-28,17:30:00,2023-10-28,21:00:00,\N,\N,1981-onwards
1099,1118,2023,21,18,São Paulo Grand Prix,2023-11-05,17:00:00,https://en.wikipedia.org/wiki/2023_S%C3%A3o_Pa...,2023-11-03,14:30:00,2023-11-04,14:30:00,\N,\N,2023-11-03,18:00:00,2023-11-04,18:30:00,1981-onwards
1100,1119,2023,22,80,Las Vegas Grand Prix,2023-11-19,06:00:00,https://en.wikipedia.org/wiki/2023_Las_Vegas_G...,2023-11-17,04:30:00,2023-11-17,08:00:00,2023-11-18,04:30:00,2023-11-18,08:00:00,\N,\N,1981-onwards
1101,1120,2023,23,24,Abu Dhabi Grand Prix,2023-11-26,13:00:00,https://en.wikipedia.org/wiki/2023_Abu_Dhabi_G...,2023-11-24,09:30:00,2023-11-24,13:00:00,2023-11-25,10:30:00,2023-11-25,14:00:00,\N,\N,1981-onwards

<font size = "5">

(4) Aggregate and sort

<font size = "3">

Import the data from "sprint_results.csv" and assign it to a DataFrame (or use the same DataFrame you created in problem (2)). Do the following:

- Group by "driverId", and then aggregate the average (mean) over the "laps" column.
- Sort the teams by average laps in **descending** order using ``.sort_values()``. Assign this to a DataFrame with a name of your choice.

For full credit, perform both steps in bullet points above in a **single line** using chaining. (If you use line breaks or wrap in parentheses it doesn't literally need to be one line).

**Hint:** Same hint as problem 2. You can chain commands together later.

In [18]:
# Your answer here

(sprint.groupby("driverId")
    .agg(avg_laps = ("laps", "mean"))
    .sort_values(by = "avg_laps", ascending = False))

           avg_laps
driverId
825       22.666667
1         21.166667
832       21.166667
854       21.166667
852       21.166667
849       21.166667
847       21.166667
846       21.166667
844       21.166667
839       21.166667
840       21.166667
830       21.166667
822       21.166667
817       21.166667
815       21.000000
20        20.833333
8         20.500000
841       19.666667
853       19.666667
848       18.666667
842       18.166667
9         18.000000
4         17.333333
855       15.666667

<font size = "5">

(5) Rename column

<font size = "3">

- Import the data from "sprint_results.csv" and assign it to a DataFrame (or use the same DataFrame you created in problem (2))

- Rename the column "time" to "time_unformatted". The names of the other columns should be left intact.

- Print (or display) the DataFrame to ensure the column was renamed correctly.

In [20]:
# Your answer here

sprint = sprint.rename(columns = {"time": "time_unformatted"})
sprint

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time_unformatted,milliseconds,fastestLap,fastestLapTime,statusId,max_lap
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1,NaN
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1,NaN
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1,NaN
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1,NaN
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,116,1095,840,117,18,15,16,16,16,0,24,+50.700,1862007,4,1:15.425,1,NaN
116,117,1095,839,214,31,6,17,17,17,0,24,+51.756,1863063,5,1:16.097,1,NaN
117,118,1095,4,214,14,7,18,18,18,0,24,+53.985,1865292,5,1:14.764,1,NaN
118,119,1095,849,3,6,16,19,19,19,0,24,+1:16.850,1888157,4,1:16.525,1,NaN
119,120,1095,848,3,23,11,\N,R,20,0,12,\N,\N,4,1:15.998,31,NaN

<font size = "5">

(6) Merge dataset

<font size = "3">

- Import the data from "sprint_results.csv" and "constructors.csv", assigning them to two DataFrames (you can also re-use the DataFrames you created above.)

- Create a new dataset with  ``pd.merge()``. Treat "sprint_results.csv" as the primary dataset and "constructors.csv" as the secondary dataset. The merge should be based on the column "constructorId".
the column "constructorId"
- To get full credit **ONLY** merge the "nationality" column from the secondary dataset (not all the columns)
- Print (or display) the resulting merged DataFrame to the screen.

**Hint**: Before you start typing "pd.merge(...)" try printing out the two DataFrames you want to merge, excluding any columns that shouldn't be included.

In [21]:
# Your answer here

df_merged = pd.merge(
    left = sprint,
    right = constructors[["constructorId", "nationality"]],
    on = "constructorId",
    how = "left"
)

df_merged

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time_unformatted,milliseconds,fastestLap,fastestLapTime,statusId,max_lap,nationality
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1,NaN,Austrian
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1,NaN,German
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1,NaN,German
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1,NaN,Italian
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1,NaN,UK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,116,1095,840,117,18,15,16,16,16,0,24,+50.700,1862007,4,1:15.425,1,NaN,UK
116,117,1095,839,214,31,6,17,17,17,0,24,+51.756,1863063,5,1:16.097,1,NaN,French
117,118,1095,4,214,14,7,18,18,18,0,24,+53.985,1865292,5,1:14.764,1,NaN,French
118,119,1095,849,3,6,16,19,19,19,0,24,+1:16.850,1888157,4,1:16.525,1,NaN,UK
119,120,1095,848,3,23,11,\N,R,20,0,12,\N,\N,4,1:15.998,31,NaN,UK